language: cpp

compiler:
    - clang
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y qttools5-dev-tools

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make
