language: cpp
sudo: required
dist: xenial
cache: apt

compiler:
    - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y qttools5-dev
  - sudo apt-get install -y qttools5-dev-tools
before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
  email: false