sudo: false
language: cpp
addons:
  apt:
    packages:
    - cmake
    - qttools5-dev
compiler:
    - clang
before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
  email: false